// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3tMgHNRqDPbuJ450QfSmNh-v7N2FDoE',
    appId: '1:791999502514:web:34fa8911671ffee4e3d1ab',
    messagingSenderId: '791999502514',
    projectId: 'online-course-app-3b93b',
    authDomain: 'online-course-app-3b93b.firebaseapp.com',
    storageBucket: 'online-course-app-3b93b.appspot.com',
    measurementId: 'G-D0CCG96LR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2nM6wPHV49DpIuh2iIGnaiHAyBsGQfd4',
    appId: '1:791999502514:android:91485061546ef008e3d1ab',
    messagingSenderId: '791999502514',
    projectId: 'online-course-app-3b93b',
    storageBucket: 'online-course-app-3b93b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABiuK7i85dnrNTNmfcl4IpeTa4aemQWFk',
    appId: '1:791999502514:ios:35f5a95e60f4b18be3d1ab',
    messagingSenderId: '791999502514',
    projectId: 'online-course-app-3b93b',
    storageBucket: 'online-course-app-3b93b.appspot.com',
    iosBundleId: 'com.example.onlineCourseApp',
  );
}
